// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: filecache.proto

package cache

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type File_Opt int32

const (
	File_Opt_unkonw File_Opt = 0
	File_Opt_put    File_Opt = 1
	File_Opt_del    File_Opt = 2
)

// Enum value maps for File_Opt.
var (
	File_Opt_name = map[int32]string{
		0: "unkonw",
		1: "put",
		2: "del",
	}
	File_Opt_value = map[string]int32{
		"unkonw": 0,
		"put":    1,
		"del":    2,
	}
)

func (x File_Opt) Enum() *File_Opt {
	p := new(File_Opt)
	*p = x
	return p
}

func (x File_Opt) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (File_Opt) Descriptor() protoreflect.EnumDescriptor {
	return file_filecache_proto_enumTypes[0].Descriptor()
}

func (File_Opt) Type() protoreflect.EnumType {
	return &file_filecache_proto_enumTypes[0]
}

func (x File_Opt) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use File_Opt.Descriptor instead.
func (File_Opt) EnumDescriptor() ([]byte, []int) {
	return file_filecache_proto_rawDescGZIP(), []int{0}
}

type ProtoVal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timeout int64  `protobuf:"varint,1,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Data    []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ProtoVal) Reset() {
	*x = ProtoVal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_filecache_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProtoVal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoVal) ProtoMessage() {}

func (x *ProtoVal) ProtoReflect() protoreflect.Message {
	mi := &file_filecache_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoVal.ProtoReflect.Descriptor instead.
func (*ProtoVal) Descriptor() ([]byte, []int) {
	return file_filecache_proto_rawDescGZIP(), []int{0}
}

func (x *ProtoVal) GetTimeout() int64 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *ProtoVal) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ProtoCache struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Datas map[string]*ProtoVal `protobuf:"bytes,1,rep,name=datas,proto3" json:"datas,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *ProtoCache) Reset() {
	*x = ProtoCache{}
	if protoimpl.UnsafeEnabled {
		mi := &file_filecache_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProtoCache) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoCache) ProtoMessage() {}

func (x *ProtoCache) ProtoReflect() protoreflect.Message {
	mi := &file_filecache_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoCache.ProtoReflect.Descriptor instead.
func (*ProtoCache) Descriptor() ([]byte, []int) {
	return file_filecache_proto_rawDescGZIP(), []int{1}
}

func (x *ProtoCache) GetDatas() map[string]*ProtoVal {
	if x != nil {
		return x.Datas
	}
	return nil
}

type Opt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type    File_Opt `protobuf:"varint,1,opt,name=type,proto3,enum=File_Opt" json:"type,omitempty"`
	Key     string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Timeout int64    `protobuf:"varint,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Data    []byte   `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Opt) Reset() {
	*x = Opt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_filecache_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Opt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Opt) ProtoMessage() {}

func (x *Opt) ProtoReflect() protoreflect.Message {
	mi := &file_filecache_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Opt.ProtoReflect.Descriptor instead.
func (*Opt) Descriptor() ([]byte, []int) {
	return file_filecache_proto_rawDescGZIP(), []int{2}
}

func (x *Opt) GetType() File_Opt {
	if x != nil {
		return x.Type
	}
	return File_Opt_unkonw
}

func (x *Opt) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Opt) GetTimeout() int64 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *Opt) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type OptList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lists []*Opt `protobuf:"bytes,1,rep,name=lists,proto3" json:"lists,omitempty"`
}

func (x *OptList) Reset() {
	*x = OptList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_filecache_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OptList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptList) ProtoMessage() {}

func (x *OptList) ProtoReflect() protoreflect.Message {
	mi := &file_filecache_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptList.ProtoReflect.Descriptor instead.
func (*OptList) Descriptor() ([]byte, []int) {
	return file_filecache_proto_rawDescGZIP(), []int{3}
}

func (x *OptList) GetLists() []*Opt {
	if x != nil {
		return x.Lists
	}
	return nil
}

var File_filecache_proto protoreflect.FileDescriptor

var file_filecache_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x66, 0x69, 0x6c, 0x65, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x38, 0x0a, 0x08, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x56, 0x61, 0x6c, 0x12, 0x18, 0x0a,
	0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07,
	0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x7f, 0x0a, 0x0a, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x43, 0x61, 0x63, 0x68, 0x65, 0x12, 0x2c, 0x0a, 0x05, 0x64, 0x61, 0x74,
	0x61, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x43, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x52, 0x05, 0x64, 0x61, 0x74, 0x61, 0x73, 0x1a, 0x43, 0x0a, 0x0a, 0x44, 0x61, 0x74, 0x61, 0x73,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x1f, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x56, 0x61,
	0x6c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x64, 0x0a, 0x03,
	0x4f, 0x70, 0x74, 0x12, 0x1d, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x09, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x5f, 0x4f, 0x70, 0x74, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x22, 0x25, 0x0a, 0x07, 0x4f, 0x70, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1a, 0x0a,
	0x05, 0x6c, 0x69, 0x73, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x04, 0x2e, 0x4f,
	0x70, 0x74, 0x52, 0x05, 0x6c, 0x69, 0x73, 0x74, 0x73, 0x2a, 0x28, 0x0a, 0x08, 0x46, 0x69, 0x6c,
	0x65, 0x5f, 0x4f, 0x70, 0x74, 0x12, 0x0a, 0x0a, 0x06, 0x75, 0x6e, 0x6b, 0x6f, 0x6e, 0x77, 0x10,
	0x00, 0x12, 0x07, 0x0a, 0x03, 0x70, 0x75, 0x74, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x64, 0x65,
	0x6c, 0x10, 0x02, 0x42, 0x07, 0x5a, 0x05, 0x63, 0x61, 0x63, 0x68, 0x65, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_filecache_proto_rawDescOnce sync.Once
	file_filecache_proto_rawDescData = file_filecache_proto_rawDesc
)

func file_filecache_proto_rawDescGZIP() []byte {
	file_filecache_proto_rawDescOnce.Do(func() {
		file_filecache_proto_rawDescData = protoimpl.X.CompressGZIP(file_filecache_proto_rawDescData)
	})
	return file_filecache_proto_rawDescData
}

var file_filecache_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_filecache_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_filecache_proto_goTypes = []interface{}{
	(File_Opt)(0),      // 0: File_Opt
	(*ProtoVal)(nil),   // 1: ProtoVal
	(*ProtoCache)(nil), // 2: ProtoCache
	(*Opt)(nil),        // 3: Opt
	(*OptList)(nil),    // 4: OptList
	nil,                // 5: ProtoCache.DatasEntry
}
var file_filecache_proto_depIdxs = []int32{
	5, // 0: ProtoCache.datas:type_name -> ProtoCache.DatasEntry
	0, // 1: Opt.type:type_name -> File_Opt
	3, // 2: OptList.lists:type_name -> Opt
	1, // 3: ProtoCache.DatasEntry.value:type_name -> ProtoVal
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_filecache_proto_init() }
func file_filecache_proto_init() {
	if File_filecache_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_filecache_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProtoVal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_filecache_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProtoCache); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_filecache_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Opt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_filecache_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OptList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_filecache_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_filecache_proto_goTypes,
		DependencyIndexes: file_filecache_proto_depIdxs,
		EnumInfos:         file_filecache_proto_enumTypes,
		MessageInfos:      file_filecache_proto_msgTypes,
	}.Build()
	File_filecache_proto = out.File
	file_filecache_proto_rawDesc = nil
	file_filecache_proto_goTypes = nil
	file_filecache_proto_depIdxs = nil
}
